name: Feature request
description: Suggest an improvement
labels: [enhancement]
body:
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Both
        - macOS
        - Linux
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: What would you like to see?
      description: The problem you are trying to solve matters more than the exact solution.
    validations:
      required: true
